=== thanhtuanxzx/xml-nguyenthanhtuan-ktpm2211056/buoi_03/bai_1/sinhvien.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- gá»‘c: <sinhviens> -->
  <xs:element name="sinhviens">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sinhvien" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="hoten" type="xs:string"/>
              <xs:element name="ngaysinh" type="xs:date"/>
              <xs:element name="chuyennganh" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== thanhtuanxzx/xml-nguyenthanhtuan-ktpm2211056/buoi_03/bai_1/sinhvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<sinhviens xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="sinhvien.xsd">

    <sinhvien id="SV01">
        <hoten>Nguyễn Văn An</hoten>
        <ngaysinh>1998-05-12</ngaysinh>
        <chuyennganh>Công nghệ thông tin</chuyennganh>
    </sinhvien>

    <sinhvien id="SV02">
        <hoten>Trần Thị Bình</hoten>
        <ngaysinh>1999-11-20</ngaysinh>
        <chuyennganh>Kinh tế</chuyennganh>
    </sinhvien>

</sinhviens>
