=== thanhtuanxzx/xml-nguyenthanhtuan-ktpm2211056/buoi_03/bai_1/thuvien.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- gá»‘c: <thuvien> -->
  <xs:element name="thuvien">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="sach" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="author" type="xs:string"/>
              <xs:element name="year" type="xs:gYear"/>
              <xs:element name="genre" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== thanhtuanxzx/xml-nguyenthanhtuan-ktpm2211056/buoi_03/bai_1/thuvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<thuvien xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="thuvien.xsd">

    <sach id="B001">
        <title>Lập trình Java</title>
        <author>Nguyễn Văn A</author>
        <year>2018</year>
        <genre>Khoa học máy tính</genre>
    </sach>

    <sach id="B002">
        <title>Kinh tế học đại cương</title>
        <author>Trần Thị B</author>
        <year>2020</year>
        <genre>Kinh tế</genre>
    </sach>

</thuvien>
