=== thanhtuanxzx/xml-nguyenthanhtuan-ktpm2211056/buoi_02/sinhvien.dtd
<!ELEMENT sinhviens (sinhvien+)>
<!ELEMENT sinhvien (hoten, ngaysinh, chuyennganh)>
<!ATTLIST sinhvien
          id ID #REQUIRED>
<!ELEMENT hoten (#PCDATA)>
<!ELEMENT ngaysinh (#PCDATA)>
<!ELEMENT chuyennganh (#PCDATA)>

=== thanhtuanxzx/xml-nguyenthanhtuan-ktpm2211056/buoi_02/sinhvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sinhviens SYSTEM "sinhvien.dtd">
<sinhviens>
  <sinhvien id="SV001">
    <hoten>Nguyễn Văn An</hoten>
    <ngaysinh>2002-05-12</ngaysinh>
    <chuyennganh>Công nghệ Thông tin</chuyennganh>
  </sinhvien>

  <sinhvien id="SV002">
    <hoten>Trần Thị Bình</hoten>
    <ngaysinh>2001-11-23</ngaysinh>
    <chuyennganh>Hệ thống Thông tin</chuyennganh>
  </sinhvien>
</sinhviens>
