=== thanhtuanxzx/xml-nguyenthanhtuan-ktpm2211056/buoi_02/dtd-buoi_01/benhvien.dtd
<!ELEMENT hospital (appointment+)>
<!ELEMENT appointment (patient, doctor)>
<!ELEMENT patient (name, dob)>
<!ELEMENT doctor (name, specialty)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT specialty (#PCDATA)>

<!ATTLIST appointment
    id CDATA #REQUIRED
    date CDATA #REQUIRED
    status CDATA #REQUIRED>

<!ATTLIST patient
    id CDATA #REQUIRED>

<!ATTLIST doctor
    id CDATA #REQUIRED>

=== thanhtuanxzx/xml-nguyenthanhtuan-ktpm2211056/buoi_01/benhvien.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hospital SYSTEM "../buoi_02/dtd-buoi_01/benhvien.dtd">
<hospital>

    <appointment id="A001" date="2025-09-16" status="Đã khám">
        <patient id="P001">
            <name>Nguyễn Thành Tuấn</name>
            <dob>2003-04-12</dob>
        </patient>
        <doctor id="D001">
            <name>Trần Văn Minh</name>
            <specialty>Nội khoa</specialty>
        </doctor>
    </appointment>

    <appointment id="A002" date="2025-09-20" status="Chưa khám">
        <patient id="P002">
            <name>Phạm Thị Hoa</name>
            <dob>1998-11-23</dob>
        </patient>
        <doctor id="D002">
            <name>Lê Thị Hạnh</name>
            <specialty>Nhi khoa</specialty>
        </doctor>
    </appointment>

</hospital>
